[package]
name                 = "blog_api"
version              = "0.1.0"
authors              = ["miyatin <kei@kamasu.jp>"]

[dependencies]
nickel               = "*"
postgres             = "0.9"
rustc-serialize      = "0.3"
time                 = "0.1"